name: release
on: [push]
jobs:
  fetch-secrets-from-conjur:
    runs-on: [self-hosted,macOS,ARM64]
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: step01
        uses: cyberark/conjur-action@v2.0.4
        with:
          url: https://emeadevops.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: kk-github
          secrets: data/vault/kk-secrets/Database-MySQL-1.1.1.0-admin/username|username;data/vault/kk-secrets/Database-MySQL-1.1.1.0-admin/password|password
      - name: step02
        run: |
          echo -n 'Retrieved username [ '
          echo -n $USERNAME | sed 's/./& /g'
          echo -n '] and password [ '
          echo -n $PASSWORD | sed 's/./& /g'
          echo ']'
